blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView # new

from posts.views import (
    PracticeView,
    VoteView,
    IndexView,
    SearchView,
    blog_category,
    blog_tags,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    ContactView,
    upload,
    user_dashboard  
    )
from marketing.views import email_list_signup

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', index),
    path('', IndexView.as_view(), name='home'),
    # path('blog/', post_list, name='post-list'),
    path('blog/', PostListView.as_view(), name='post-list'),
    path('search/', SearchView.as_view(), name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    # path('create/', post_create, name='post-create'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('upload/', upload, name='upload_img'),
    # path('post/<id>/', post_detail, name='post-detail'),
    path('post/<str:slug>-<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/<id>/update/', post_update, name='post-update'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<id>/delete/', post_delete, name='post-delete'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('contact/', ContactView, name='contact'),
    path('vote/', VoteView, name='vote_post'),
    path('practice/', PracticeView, name='practice'),
    
    path('searchbycat/<category>/', blog_category, name='searchbycat'),
    path('searchbytag/<tags>/', blog_tags, name='searchbytag'),
    
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/',
         user_dashboard.as_view(),
         name='profile')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
                           

posts/models.py
from tinymce.models import HTMLField
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.template.defaultfilters import slugify
from tinymce import models as tinymce_models

User = get_user_model()


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    authorname = models.CharField(max_length=100)
    aboutme = models.CharField(max_length=300)
    desination = models.CharField(max_length=100)
    profile_picture = models.ImageField(blank=True,null=True)


    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

class Tags(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null = False)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    content = tinymce_models.HTMLField(blank=True)
    # comment_count = models.IntegerField(default = 0)
    # view_count = models.IntegerField(default = 0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField()
    votes = models.ManyToManyField(User, related_name='blog_posts', blank=True)
    tags =  models.ManyToManyField(Tags)
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'pk': self.pk,
            'slug': self.slug
        })

    def get_update_url(self):
        return reverse('post-update', kwargs={
            'pk': self.pk
        })

    def get_delete_url(self):
        return reverse('post-delete', kwargs={
            'pk': self.pk
        })

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value)
        super().save(*args, **kwargs)

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

    @property
    def vote_count(self):
        return self.votes.count()

    @property
    def get_tags(self):
        return Tags.objects.filter(post=self)

    @property
    def get_authordetails(self):
        return Author.objects.get(post=self)

posts/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Post, Comment


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    # content = forms.CharField(
    #     widget=TinyMCEWidget(
    #         attrs={'required': False, 'cols': 30, 'rows': 10, 'id': 'postcontent'}
    #     )
    # )

    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your Content',
        'id': 'postcontent',
        'rows': '8'
    }))

    class Meta:
        model = Post
        fields = ('title', 'overview', 'content', 'thumbnail', 
        'categories','tags','featured', 'previous_post', 'next_post')


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '5'
    }))
    class Meta:
        model = Comment
        fields = ('content', )

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

posts/views.py
from django.http import JsonResponse
from django.db.models import Count, Q
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import CommentForm, PostForm
from .models import Post, Author, PostView,Comment
from marketing.forms import EmailSignupForm
from marketing.models import Signup
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.template.defaultfilters import slugify
from django.core.mail import send_mail
from django.conf import settings

from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.http import HttpResponse
import uuid


form = EmailSignupForm()


def get_author(user):
    qs = Author.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None

def get_category_count():
    queryset = Post \
        .objects \
        .values('categories__title') \
        .annotate(Count('categories__title'))
    return queryset

def get_tags_count():
    queryset = Post \
        .objects \
        .values('tags__title') \
        .annotate(Count('tags__title'))
    return queryset

class SearchView(View):
    def get(self, request, *args, **kwargs):
        queryset = Post.objects.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(overview__icontains=query)
            ).distinct()
        context = {
            'queryset': queryset
        }
        return render(request, 'search_results.html', context)


def blog_category(request, category):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post_list = Post.objects.filter(
        categories__title=category
    )
    tags = get_tags_count()
    paginator = Paginator(post_list, 4)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        paginated_queryset = paginator.page(paginator.num_pages)

    context = {
        'queryset': paginated_queryset,
        'most_recent': most_recent,
        'page_request_var': page_request_var,
        'category_count': category_count,
        'tags': tags,
        'form': form
    }
    return render(request, 'blog.html', context)


def ContactView(request):
    message_email = ""
    if request.method == 'POST':
        message_email = request.POST['email'] 
        message_subject  = request.POST['subject'] 
        message  = request.POST['message']
        #send a email
        send_mail(message_subject, message, settings.EMAIL_HOST_USER, [message_email])

    return render(request, "contacts.html", {'msg': message_email})


def blog_tags(request, tags):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post_list = Post.objects.filter(
        tags__title=tags
    )
    tags = get_tags_count()
    paginator = Paginator(post_list, 4)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        paginated_queryset = paginator.page(paginator.num_pages)

    context = {
        'queryset': paginated_queryset,
        'most_recent': most_recent,
        'page_request_var': page_request_var,
        'category_count': category_count,
        'tags': tags,
        'form': form
    }
    return render(request, 'blog.html', context)






class IndexView(View):
    form = EmailSignupForm()

    def get(self, request, *args, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.filter(featured=True).order_by('-timestamp')[:3]
        post_list = Post.objects.filter(featured=True).all()
        tags = get_tags_count()
        paginator = Paginator(post_list, 2)
        page_request_var = 'page'
        page = request.GET.get(page_request_var)
        try:
            paginated_queryset = paginator.page(page)
        except PageNotAnInteger:
            paginated_queryset = paginator.page(1)
        except EmptyPage:
            paginated_queryset = paginator.page(paginator.num_pages)
        context = {
            'object_list': paginated_queryset,
            'most_recent': most_recent, 
            'page_request_var': page_request_var,
            'category_count': category_count,
            'tags': tags,
            'form': self.form
        }
        return render(request, 'index.html', context)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        new_signup = Signup()
        new_signup.email = email
        new_signup.save()
        messages.info(request, "Successfully subscribed")
        return redirect("home")





class PostListView(ListView):
    form = EmailSignupForm()
    model = Post
    template_name = 'blog.html'
    context_object_name = 'queryset'
    paginate_by =2

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.filter(featured=True).order_by('-timestamp')[:3]
        tags = get_tags_count()
        context = super().get_context_data(**kwargs)
        context['most_related'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['tags'] = tags
        context['form'] = self.form
        return context



class PostDetailView(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'
    form = CommentForm()

    def get_object(self):
        obj = super().get_object()
        if self.request.user.is_authenticated:
            PostView.objects.get_or_create(
                user=self.request.user,
                post=obj
            )
        return obj

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        post = get_object_or_404(Post, id= self.kwargs['pk'])
        rhs_tags = get_tags_count()
        most_relative = Post.objects.order_by('-timestamp')[:3]
        liked = False
        if post.votes.filter(id = self.request.user.id).exists():
            liked = True
        current_author = get_author(self.request.user)
        userpostcount = post_count(current_author)
        author_votecount = 0
        for n in Post.objects.filter(author=current_author):
            author_votecount += n.votes.count()

        context = super().get_context_data(**kwargs)
        context['most_relative'] = most_relative
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['liked'] = liked
        context['vote_count'] = post.vote_count
        context['tags'] = post.get_tags[0],
        context['rhs_tags'] = rhs_tags[0]
        context['author_details'] = post.get_authordetails
        context['authorpostcount'] = userpostcount
        context['authorvotecount'] = author_votecount
        
        
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'pk': post.pk   
            }))


class PostCreateView(CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context

   
    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.author = get_author(self.request.user)
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'pk': form.instance.pk,
                'slug': slugify(form.instance.title)
            }))
        else:
            return redirect("/accounts/login")



 

def upload(request):
    try:
        file = request.FILES['docf']
        updatedImgName = str(uuid.uuid4())
        imgExt = file.name.split('.')[1]
        img = Image.open(file)
        img.thumbnail((500, 500), Image.ANTIALIAS)
        try:
            img.save(settings.MEDIA_ROOT+"/blog_img/" + updatedImgName+"."+imgExt)
            print("img save pass")
        except:
            print("img.save error")
        path = "/media/blog_img/" + updatedImgName+"."+imgExt

        return JsonResponse({"imgpath": path}, status=200)
    except Exception:
        return HttpResponse("error")

class PostUpdateView(UpdateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update'
        return context

    def form_valid(self, form):
        form.instance.author = get_author(self.request.user)
        form.save()
        return redirect(reverse("post-detail", kwargs={
            'pk': form.instance.pk,
            'slug': slugify(form.instance.title)
        }))

def VoteView(request):
    iddy = request.POST.get('post_id')
    if request.method == 'POST':
        post = get_object_or_404(Post, id= iddy)
        liked = False
        if post.votes.filter(id = request.user.id).exists():
            post.votes.remove(request.user)

templates/base.html
<!DOCTYPE html>
<html>

    {% block head %}
    {% endblock head %}

<body>

    {% include 'header.html'%}
    
    
    {% block content %}
    
    {% endblock content %}

    {% include 'footer.html' %}
    {% include 'scripts.html' %}

</body>

</html>

templates/footer.html
{% load static %}
<!-- =-=-=-=-=-=-= FOOTER =-=-=-=-=-=-= -->
<footer class="footer-area">

    <!--Footer Upper-->
    <div class="footer-content">
      <div class="container">
        <div class="row clearfix">
          <div class="col-md-8 col-md-offset-2">
            <div class="footer-content text-center no-padding margin-bottom-40">
              <div class="logo-footer"><img id="logo-footer" class="center-block" src="{% static 'images/logo.png' %}" alt="">
              </div>
              <p>We have started free blogging system. Here you can create and post your own articles. User can also get a lot's of knowledge about machine learning and other techknowlogy.</p>
              <p>We are very happy to read your articles. It is fully free community article website.</p>
            </div>
          </div>

          <!--Two 4th column-->
          <div class="col-md-6 col-sm-12 col-xs-12">
            <div class="row clearfix">
              <div class="col-lg-7 col-sm-6 col-xs-12 column">
                <div class="footer-widget about-widget">
                  <h2>Our Addres</h2>
                  <ul class="contact-info">
                    <li><span class="icon fa fa-map-marker"></span> Dwarka, Delhi</li>
                    <li><span class="icon fa fa-phone"></span> (+091) 8800225812</li>
                    <li><span class="icon fa fa-mail"></span> blog@pkarticle.com</li>
                  </ul>
                </div>
              </div>

              <!--Footer Column-->
              <div class="col-lg-5 col-sm-6 col-xs-12 column">
                <h2>Our Service</h2>
                <div class="footer-widget links-widget">
                  <ul>
                    <li><a href="#">Data Scientiest</a>
                    </li>
                    <li><a href="#">Data Analysis</a>
                    </li>
                    <li><a href="#">Web Development</a>
                    </li>
                    <li><a href="#">Android Development</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!--Two 4th column End-->

          <!--Two 4th column-->
          <div class="col-md-6 col-sm-12 col-xs-12">
            <div class="row clearfix">
              <!--Footer Column-->
              <div class="col-lg-7 col-sm-6 col-xs-12 column">
                <div class="footer-widget news-widget">
                  <h2>Latest News</h2>

                  <!--News Post-->
                  <div class="news-post">
                    <div class="icon"></div>
                    <div class="news-content">
                      <figure class="image-thumb"><img src="{% static 'images/blog/popular-2.jpg' %}" alt="">
                      </figure>
                      <a href="#">we have started new develop</a>
                    </div>
                    <div class="time">March 3, 2021</div>
                  </div>

                </div>
              </div>

              <!--Footer Column-->
              <div class="col-lg-5 col-sm-6 col-xs-12 column">
                <div class="footer-widget links-widget">
                  <h2>Site Links</h2>
                  <ul>
                    <li><a href="{% url 'account_login'%}">Login</a>
                    </li>
                    <li><a href="{% url 'account_signup'%}">Register</a>
                    </li>
                    <li><a href="{% url 'post-list'%}">Articles</a>
                    </li>
                    <li><a href="#">Contact Us</a>
                    </li>

                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!--Two 4th column End-->

        </div>
      </div>
    </div>

    <!--Footer Bottom-->
    <div class="footer-copyright">
      <div class="auto-container clearfix">
        <!--Copyright-->
        <div class="copyright text-center">Copyright 2016 &copy;  All Rights Reserved by <b>DataScienceMastery</b></div>
      </div>
    </div>
  </footer>

templates/post_create.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block head %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="ScriptsBundle">
    <title>{{ post.title }}</title>
    <!-- =-=-=-=-=-=-= Favicons Icon =-=-=-=-=-=-= -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <!-- =-=-=-=-=-=-= Mobile Specific =-=-=-=-=-=-= -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <!-- =-=-=-=-=-=-= Bootstrap CSS Style =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- =-=-=-=-=-=-= Template CSS Style =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- =-=-=-=-=-=-= Font Awesome =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <!-- =-=-=-=-=-=-= Et Line Fonts =-=-=-=-=-=-= -->
    <link rel="stylesheet" href="{% static 'css/et-line-fonts.css' %}">
        <!-- =-=-=-=-=-=-= Owl carousel =-=-=-=-=-=-= -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/owl.style.css' %}">
    <!-- =-=-=-=-=-=-= Google Fonts =-=-=-=-=-=-= -->
    
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic|Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css">
    <!-- =-=-=-=-=-=-= Highliter Css =-=-=-=-=-=-= -->
    <link type="text/css" rel="Stylesheet" href="{% static 'css/styles/shCoreDefault.css' %}" />
    <!-- =-=-=-=-=-=-= Css Animation =-=-=-=-=-=-= -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/animate.min.css' %}" />
    <!-- =-=-=-=-=-=-= Hover Dropdown =-=-=-=-=-=-= -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap-dropdownhover.min.css' %}" />
    <!-- JavaScripts -->
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
      <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
     -->
     
     <meta name="title" content="Data Science Mastery">
     <meta name="description" content="Free articles and blogger websiet for machine learning and deep learning, django, python">
     <meta name="keywords" content="python, flask, streamlit, C#, .Net, machine learning, deep learning, django, blog, article, software">
     <meta name="robots" content="index, nofollow">
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
     <meta name="language" content="English">
     <meta name="revisit-after" content="1 days">
     <meta name="author" content="Praveen Singh">
 
     <meta property="og:site_name" content="Learn DataScience and Machine learning by DataScienceMastery"/>
     <meta property="og:type" content="article" />
     <meta property="og:title" content="Data Science Mastery and Machine Learning" />
     <meta property="og:description" content="Free articles and blogger websiet for machine learning and deep learning, django, python" />
     <meta property="og:url" content="https://DataScienceMastery.in"/>
     <meta property="article:tag" content="Data Science"/>
     <meta property="article:tag" content="machine learning" />
     <meta property="article:tag" content="deep learning" />
     <meta property="article:tag" content="beginner articles for machine learning" />
     <meta property="article:tag" content="beginner articles for deep learning" />
     <meta property="article:tag" content="beginner and advance for python" />
     <meta property="article:tag" content="beginner and advance for django" />
     <meta property="article:tag" content="beginner and advance for flask" />
     <meta property="article:tag" content="free a lot of tools for machine learning" />
     <meta property="article:tag" content="EDA and Hyper parameter tunning" />
     <meta property="article:tag" content="streamlit blog and tutorial for streamlit" />
 
</head>
{% endblock head %}


{% block content %}
<script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
<script src="//cloud.tinymce.com/stable/tinymce.min.js"></script>
<script>
  $(document).ready(function() {
      // $('#sub').on('click', function() {
      //     // tinyMCE.triggerSave();
      //     // alert($("#post_content").val())
      //     var content = $("#postcontent").val()
      //     content = content.replace('src=\"../media/blog_img', 'src=\"/media/blog_img')

      //     $("#postcontent").text(content)
      //     alert($("#postcontent").val())

      // });
      tinymce.init({
        selector: "textarea#postcontent",
        images_upload_base_path: '/media',
        relative_urls: false,

        setup: function (editor) {
        editor.on('change', function () {
            tinymce.triggerSave();
        });
        },
        theme: "modern",
        paste_data_images: true,
        plugins: [
          "advlist autolink lists link image charmap print preview hr anchor pagebreak",
          "searchreplace wordcount visualblocks visualchars code fullscreen",
          "insertdatetime media nonbreaking save table contextmenu directionality",
          "emoticons template paste textcolor colorpicker textpattern codesample"
        ],
        codesample_languages: [
            {text: 'HTML/XML', value: 'markup'},
            {text: 'JavaScript', value: 'javascript'},
            {text: 'CSS', value: 'css'},
            {text: 'Python', value: 'python'},
            {text: 'Java', value: 'java'},
            {text: 'C', value: 'c'},
            {text: 'C#', value: 'csharp'}
        ],
        toolbar: 'codesample',
        toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
        toolbar2: "print preview media | forecolor backcolor emoticons",
        image_advtab: true,
        file_picker_callback: function(callback, value, meta) {
          if (meta.filetype == 'image') {
            $('#upload').trigger('click');
            $('#upload').on('change', function() {
              var titleVal = $("#id_title").val()
              var file = this.files[0];
              // var reader = new FileReader();
              var token = '{{ csrf_token }}';
              var data1 = new FormData()
              data1.append('docf', file)

              $.ajax({
                  type: 'POST',
                  url: '{% url "upload_img"  %}',
                  data: data1,
                  processData: false,
                  contentType: false,
                  headers: {'X-CSRFToken': token},
                  success: function (data) {
                    callback(data.imgpath, {alt: titleVal});
                  }
              });

            });
          }
        },
        templates: [{
          title: 'Test template 1',
          content: 'Test 1'
        }, {
          title: 'Test template 2',
          content: 'Test 2'
        }]
      });
    });
</script>
<section class="section-padding-80 white" id="post-question">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 ">

            <div class="box-panel">
                <h2>{{ title }} an article</h2>
                {{ form.media }}
                <form method="POST" action="/create/" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form|crispy }}
                  <input name="image" type="file" id="upload" style="display: none;"/>

                    <button class="btn btn-primary"  id="sub" type="submit">Submit</button>
                </form>
            </div>
           </div>
        </div>
     </div>
</section>
{% endblock content %}